//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Записи
    {
        public Записи()
        {
            this.История_заказов = new HashSet<История_заказов>();
            this.Результат_предоставления_услуги = new HashSet<Результат_предоставления_услуги>();
        }
    
        public int Id_предоставления_услуги { get; set; }
        public Nullable<int> Id_услуги { get; set; }
        public Nullable<int> Id_клиента { get; set; }
        public Nullable<System.DateTime> Дата_время { get; set; }
        public Nullable<int> статус_услуг { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Статус_услуги Статус_услуги { get; set; }
        public virtual Услуги Услуги { get; set; }
        public virtual ICollection<История_заказов> История_заказов { get; set; }
        public virtual ICollection<Результат_предоставления_услуги> Результат_предоставления_услуги { get; set; }
        public virtual Скан_предоставления_услуги Скан_предоставления_услуги { get; set; }
    }
}
