//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class История_заказов
    {
        public int Id_история { get; set; }
        public int id_заказа { get; set; }
        public string количество_товара { get; set; }
        public Nullable<int> id_товара { get; set; }
        public Nullable<int> количество { get; set; }
        public Nullable<int> id_комплекта { get; set; }
        public string Всего_колтво { get; set; }
        public double итоговая_стоимость { get; set; }
        public string файл { get; set; }
        public string Примечание { get; set; }
        public int Статус { get; set; }
    
        public virtual Записи Записи { get; set; }
        public virtual Комплект Комплект { get; set; }
        public virtual Статус_услуги Статус_услуги { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
