//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиент
    {
        public Клиент()
        {
            this.Записи = new HashSet<Записи>();
        }
    
        public int Id_клиента { get; set; }
        public Nullable<int> Id_user { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Пол { get; set; }
        public string Номер_телефона { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Электронная_почта { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
        public string Фото { get; set; }
        public Nullable<int> Id_тип_клиента { get; set; }
    
        public virtual Авторизация Авторизация { get; set; }
        public virtual ICollection<Записи> Записи { get; set; }
        public virtual Тип_клиента Тип_клиента { get; set; }
    }
}
