//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комплект
    {
        public Комплект()
        {
            this.История_заказов = new HashSet<История_заказов>();
        }
    
        public int Id_комплект { get; set; }
        public Nullable<int> Id_товар1 { get; set; }
        public Nullable<int> Id_товар2 { get; set; }
    
        public virtual ICollection<История_заказов> История_заказов { get; set; }
        public virtual Товар Товар { get; set; }
        public virtual Товар Товар1 { get; set; }
    }
}
