//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рабочее_время_сотрудника
    {
        public int Id_рабочее_время { get; set; }
        public Nullable<int> Id_сотрудника { get; set; }
        public Nullable<int> Id_услуги { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<System.TimeSpan> Время { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
