//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public Сотрудники()
        {
            this.Рабочее_время_сотрудника = new HashSet<Рабочее_время_сотрудника>();
        }
    
        public int Id_сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Серия_номер { get; set; }
        public int Код_подразделения { get; set; }
        public string Пол { get; set; }
        public int Коэффициент_оплаты { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int Id_категория_сотрудника { get; set; }
    
        public virtual Категория_сотрудников Категория_сотрудников { get; set; }
        public virtual ICollection<Рабочее_время_сотрудника> Рабочее_время_сотрудника { get; set; }
    }
}
