//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Статус_услуги
    {
        public Статус_услуги()
        {
            this.Записи = new HashSet<Записи>();
            this.История_заказов = new HashSet<История_заказов>();
        }
    
        public int Id_статуса { get; set; }
        public string Название { get; set; }
    
        public virtual ICollection<Записи> Записи { get; set; }
        public virtual ICollection<История_заказов> История_заказов { get; set; }
    }
}
