//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тип_клиента
    {
        public Тип_клиента()
        {
            this.Клиент = new HashSet<Клиент>();
        }
    
        public int Id_тип_клиента { get; set; }
        public string Название { get; set; }
        public string Процент_скидки { get; set; }
    
        public virtual ICollection<Клиент> Клиент { get; set; }
    }
}
