//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public Товар()
        {
            this.История_заказов = new HashSet<История_заказов>();
            this.Комплект = new HashSet<Комплект>();
            this.Комплект1 = new HashSet<Комплект>();
            this.Сезонные_товары = new HashSet<Сезонные_товары>();
        }
    
        public int Id_товара { get; set; }
        public string Наименование { get; set; }
        public int Id_категории_товара { get; set; }
        public decimal Стоимость { get; set; }
        public string Характеристика { get; set; }
        public string Описание { get; set; }
        public int Вес { get; set; }
        public int Ширина { get; set; }
        public int Высота { get; set; }
        public int Длина { get; set; }
        public string Производитель { get; set; }
        public string Фото { get; set; }
        public Nullable<int> Id_склада { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Доп_фото_товар Доп_фото_товар { get; set; }
        public virtual ICollection<История_заказов> История_заказов { get; set; }
        public virtual Категория_товаров Категория_товаров { get; set; }
        public virtual ICollection<Комплект> Комплект { get; set; }
        public virtual ICollection<Комплект> Комплект1 { get; set; }
        public virtual ICollection<Сезонные_товары> Сезонные_товары { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
