//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLanguages.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Услуги
    {
        public Услуги()
        {
            this.Записи = new HashSet<Записи>();
            this.Рабочее_время_сотрудника = new HashSet<Рабочее_время_сотрудника>();
        }

        public int Id_услуги { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public string Фото { get; set; }
        public int Продолжительность { get; set; }
        public double Стоимость { get; set; }
        public Nullable<double> Скидка { get; set; }

        public virtual Доп_фото_услуг Доп_фото_услуг { get; set; }
        public virtual ICollection<Записи> Записи { get; set; }
        public virtual ICollection<Рабочее_время_сотрудника> Рабочее_время_сотрудника { get; set; }

        public string GetPhoto
        {
            get
            {
                if (Фото is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + Фото.Trim();
            }
        }

    }
}
